### ISSUE TITLE
is the InstaBoost only fit the data labeled with the object keypoint type annotations?

### ISSUE THREAD

**Issue by blissSeven** [GothicAi/InstaBoost-pypi#9]
Hi, guys. 
I use labelme to label my  data. and I test with yolact works well。But when I test with instaboost with yolact ,something goes wrong.........

Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train()
  File "train.py", line 213, in train
    for datum in data_loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/Colab/Instaboost/yolact/data/coco.py", line 90, in __getitem__
    im, gt, masks, h, w, num_crowds = self.pull_item(index)
  File "/content/drive/My Drive/Colab/Instaboost/yolact/data/coco.py", line 126, in pull_item
    target, img = get_new_data(target, img, None, background=None)
  File "/usr/local/lib/python3.6/dist-packages/instaboostfast/InstaBoost.py", line 50, in get_new_data
    background.shape[1], background.shape[0])
  File "/usr/local/lib/python3.6/dist-packages/instaboostfast/affine_transform.py", line 132, in transform_annotation
    keypoints = ann['keypoints']
KeyError: 'keypoints'

I check my image annotation  file don't has the key 'keypoints ', so  is the InstaBoost only fit the data labeled with the object keypoint type? doesn't fit the data labeled with the object instance type annotations?

**Comment by rogerwwww** [comment]
Hi, sorry for the inconvenience. InstaBoost should work fine without keypoint annotation. 

As a workaround you could checkout to ``76b7e6d1e54227d036336334752bd32e7a193200`` and it should work soundly.

The keypoint things are added by https://github.com/GothicAi/InstaBoost-pypi/pull/2 where we experimentally run InstaBoost for keypoint-related tasks (such as human pose, but note that the performance is not guaranteed) and COCO has such annotation. However, I think we should ensure the compatibility to non-keypoint annotations. So @GothicAi could you please fix this?

**Comment by GothicAi** [comment]
Hi, I have fixed this bug and you can try the newest version instaboostfast(0.1.2) or instaboost(0.2.1). Thanks!

**Comment by blissSeven** [comment]
Yeah it works，Thank you for your prompt handling
